server {
    listen 80;
    server_name domain.com www.domain.com;
    return 301 https://domain.com$request_uri;
}

server {
    listen 443 ssl;
    server_name www.domain.com;
    http2 on;

    include h5bp/hostname_ssl.conf;
    return 301 https://domain.com$request_uri;
}

server {
    listen 443 ssl;
    server_name domain.com;
    http2 on;

    include h5bp/hostname_ssl.conf;
    root      /var/www/;
    error_log /var/www/error.log;
    client_max_body_size 100m;
    
    location / {
        proxy_pass https://1.2.3.4;
        include h5bp/reverse_proxy.conf;
    }
}
