proxy_http_version 1.1;

proxy_redirect off;
proxy_ssl_verify off;
proxy_set_header Host              $host;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host  $host;
proxy_set_header X-Forwarded-Port  $server_port;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header Connection        "";

proxy_connect_timeout 100s;
proxy_send_timeout    100s;
proxy_read_timeout    100s;

proxy_buffering on;
proxy_buffer_size 32k;
proxy_buffers 512 32k;
proxy_busy_buffers_size 1m;

### proxy_cache start
proxy_cache_methods     GET HEAD;
proxy_cache_key         "$request_method$scheme$host$request_uri$cookie_xf_style_variation";
proxy_cache_lock        on;
proxy_cache_use_stale   error timeout invalid_header updating http_500 http_503;
proxy_ignore_headers    Cache-Control Expires Set-Cookie;
proxy_cache             xfproxycache; 

proxy_no_cache          $cookie_xf_lscxf_logged_in $cookie_xf_tfa_trust $cookie_xf_user $cookie_xf_session_admin $xf_proxy_cacheuri;
proxy_cache_bypass      $cookie_xf_lscxf_logged_in $cookie_xf_tfa_trust $cookie_xf_user $cookie_xf_session_admin $xf_proxy_cacheuri;

proxy_cache_valid       200     5m;
proxy_cache_valid       302     1h;
proxy_cache_valid       301 404 2h;
proxy_cache_valid       any     5s;

add_header X-Proxy-Cache $upstream_cache_status always;
### proxy_hide_header x-xf-cache-status;
### proxy_cache end
